nextgen:
  initiative: nextgen
  domain: openshiftapps
  baseImageRegistry: docker-registry.default.svc:5000
  imageRegistryNamespace: app-emerald
  repoURL: wcgartifactory-docker.jfrog.io
  routerID: 4c8f
  clusterID: wc-sb01
  conjurAccount: wellcare
  conjurHostID: authn-k8s/tampa

application: emerald
replicaCount: 2

prometheusEnabled: true
prometheusPath: /actuator/prometheus
prometheusPort: 9090

imageStreams:
  service:
    name: pb-dbp
    pullPolicy: Always
  fluentbit:
    repository: docker-registry.default.svc:5000/app-emerald/fluent-bit
    tag: 1.2.2
    pullPolicy: IfNotPresent
  jaeger:
    repository: docker-registry.default.svc:5000/app-emerald/jaeger-agent
    tag: latest
    pullPolicy: IfNotPresent
  conjurAuth:
    repository: docker-registry.default.svc:5000/app-emerald/conjur-kubernetes-authenticator
    tag: latest
    pullPolicy: IfNotPresent

service:
  httpPort: 8090
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    name: http
  - port: 9000
    targetPort: actuator
    name: actuator

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: {}

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

fluentbit:
  containerPort: 2020

jaeger:
  containerPorts:
    - containerPort: 5775
      protocol: UDP
    - containerPort: 5778
      protocol: TCP
    - containerPort: 6831
      protocol: UDP
    - containerPort: 6832
      protocol: UDP

env:
  service:
    SPRING_APPLICATION_NAME: emerald-bdp
    NEXTGEN_PLATFORM_COMPONENT: emerald-bdp
    NEXTGEN_LOG_FOLDER: /var/log/nextgen
    M2_HOME: /mvn
  jaeger:
    JAEGER_COLLECTOR_HOST_PORT: jaeger-collector.app-monitoring.svc:14267
  fluentbit:
    FLUENT_ELASTICSEARCH_HOST: elasticsearch.app-monitoring
    FLUENT_ELASTICSEARCH_PORT: 9200

conjurSecrets:
  ATLAS_CORE_SECURITY_JWT_SECRET: "!var tampa/nextgen/emerald/bdp/atlas-core-security-jwt-secret"
  SPRING_DATASOURCE_USERNAME: "!var tampa/nextgen/emerald/bdp/spring-datasource-username"
  SPRING_DATASOURCE_PASSWORD: "!var tampa/nextgen/emerald/bdp/spring-datasource-password"

resources:
  limits:
    cpu: 1000m
    memory: 768Mi
  requests:
    cpu: 500m
    memory: 512Mi

storage:
- name: trans-log
  mountPath: /transaction-logs/ShadowNoFileLockStore
  volumeSpec:
    emptyDir: {}

readinessProbe:
  failureThreshold: 2
  initialDelaySeconds: 30
  periodSeconds: 5
  path: /actuator/health
  port: actuator
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 60
  periodSeconds: 5
  path: /actuator/health
  port: actuator

nodeSelector: {}

tolerations: []

affinity: {}

deploymentStrategy:
  revisionHistoryLimit: 3
  maxSurge: 1
  maxUnavailable: 1
  type: RollingUpdate
  
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
